export const endpoints = {
  authLogin: '/api/auth/login',
  authRefresh: '/api/auth/refresh',
  authLogout: '/api/auth/logout',
  authLogoutAll: '/api/auth/logout-all',

  adminUsers: '/api/admin-users',
  languages: '/api/languages',
  placeTypes: '/api/place-types',
  contentTypes: '/api/content-types',
  targetTypes: '/api/target-types',
  translationSources: '/api/translation-sources',
  triggerModes: '/api/trigger-modes',
  geofenceEventTypes: '/api/geofence-event-types',
  geofenceEventStatuses: '/api/geofence-event-statuses',

  places: '/api/places',
  dishCategories: '/api/dish-categories',
  dishes: '/api/dishes',
  placeDishes: '/api/place-dishes',

  narrationContents: '/api/narration-contents',
  narrationTranslations: '/api/narration-translations',
  audioFiles: '/api/audio-files',
  publicNarrations: '/api/public/narrations',
  vendorNarrations: '/api/vendor/narrations',
  vendorLogin: '/api/vendor-auth/login',
  vendorRegister: '/api/vendor-auth/register',
  vendorDashboard: '/api/vendor/account/dashboard',
  vendorRenewal: '/api/vendor/account/renewal',
  vendorMockPayments: '/api/vendor/account/mock-payments',
  vendorNotifications: '/api/vendor/account/notifications',
  adminVendors: '/api/admin/vendors',
  adminVendorRenewals: '/api/admin/vendors/renewals',

  guestSessions: '/api/public/guest-sessions',
  geofenceCheck: '/api/public/geofence/check',
  listeningHistories: '/api/public/listening-histories',
  feedbacks: '/api/public/feedbacks',

  adminFeedbacks: '/api/admin/feedbacks',
  adminListeningHistories: '/api/admin/listening-histories',
  adminGeofenceEvents: '/api/admin/geofence-events',
  geocodingResolve: '/api/admin/geocoding/resolve',
  vendorRefresh: '/api/vendor-auth/refresh',
  vendorLogout: '/api/vendor-auth/logout',
  vendorProfile: '/api/vendor/account/profile',
  vendorChangePassword: '/api/vendor/account/change-password',
  vendorLogoutAll: '/api/vendor/account/logout-all',
  vendorCatalog: '/api/vendor/catalog',
  guestAccess: '/api/public/access',
  adminAuditLogs: '/api/admin/audit-logs',
  adminDashboardStatistics: '/api/admin/dashboard/statistics'
};
