export const endpoints = {
  authLogin: '/api/auth/login',
  adminUsers: '/api/admin-users',
  languages: '/api/languages',
  placeTypes: '/api/place-types',
  contentTypes: '/api/content-types',
  targetTypes: '/api/target-types',
  translationSources: '/api/translation-sources',
  triggerModes: '/api/trigger-modes',
  geofenceEventTypes: '/api/geofence-event-types',
  geofenceEventStatuses: '/api/geofence-event-statuses',
  places: '/api/places',
  dishCategories: '/api/dish-categories',
  dishes: '/api/dishes',
  placeDishes: '/api/place-dishes',
  narrationContents: '/api/narration-contents',
  narrationTranslations: '/api/narration-translations',
  audioFiles: '/api/audio-files',
  qrCodes: '/api/qr-codes',
  guestSessions: '/api/public/guest-sessions',
  qrResolve: '/api/public/qr/resolve',
  geofenceCheck: '/api/public/geofence/check',
  listeningHistories: '/api/public/listening-histories',
  feedbacks: '/api/public/feedbacks',
  adminFeedbacks: '/api/admin/feedbacks',
  adminListeningHistories: '/api/admin/listening-histories',
  adminGeofenceEvents: '/api/admin/geofence-events'
};
