import SimpleResourcePage from './SimpleResourcePage';
import { endpoints } from '../../api/endpoints';

export default function AudioManagementScreen() {
  return <SimpleResourcePage config={{ title: 'Audio Management', description: 'AudioUrl là tùy chọn. Nếu không có audio, mobile app dùng Web Speech API để đọc text.', endpoint: endpoints.audioFiles, fields: [
  {
    name: 'translationId',
    label: 'Translation',
    type: 'select',
    optionEndpoint: endpoints.narrationTranslations,
    optionValueKey: 'translationId',
    optionLabel: (translation) =>
      `${translation.translationId} - ${translation.translatedTitle} / language ${translation.languageId}`,
    required: true
  },
  { name: 'audioUrl', label: 'Audio URL', required: true },
  { name: 'voiceName', label: 'Voice Name' },
  { name: 'voiceGender', label: 'Voice Gender' },
  { name: 'durationSeconds', label: 'Duration Seconds', type: 'number', nullable: true },
  { name: 'fileFormat', label: 'File Format' },
  { name: 'generatedBy', label: 'Generated By' },
  { name: 'isActive', label: 'Active', type: 'checkbox' }
], columns: [
    { key: 'audioId', label: 'Id' }, { key: 'translationId', label: 'Translation' }, { key: 'audioUrl', label: 'URL' }, { key: 'fileFormat', label: 'Format' }, { key: 'isActive', label: 'Active', render: r => r.isActive ? 'Yes' : 'No' }
  ] }} />;
}
