CREATE DATABASE vinh_khanh_narration_db 




—
-- =========================================================
-- DATABASE SCHEMA
-- Project: Multilingual Automatic Narration for Vinh Khanh Food Street
-- DBMS: PostgreSQL
-- Database: vinh_khanh_narration_db
-- =========================================================


-- =========================================================
-- 1. ADMIN USERS
-- Tài khoản nội bộ: Admin, ContentManager, Translator, Reviewer
-- Role fix cứng bằng CHECK constraint
-- =========================================================

CREATE TABLE admin_users (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,

    role VARCHAR(50) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_admin_users_role
        CHECK (role IN ('Admin', 'ContentManager', 'Translator', 'Reviewer'))
);


-- =========================================================
-- 2. LANGUAGES
-- Danh sách ngôn ngữ hệ thống hỗ trợ
-- =========================================================

CREATE TABLE languages (
    language_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    language_code VARCHAR(10) NOT NULL UNIQUE,
    language_name VARCHAR(100) NOT NULL,

    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 3. PLACES
-- Địa điểm / quán ăn / khu vực ở phố ẩm thực Vĩnh Khánh
-- =========================================================

CREATE TABLE places (
    place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    place_name VARCHAR(150) NOT NULL,
    place_type VARCHAR(50) NOT NULL,

    address VARCHAR(255),
    description TEXT,

    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),

    opening_hours VARCHAR(100),
    image_url VARCHAR(500),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_places_place_type
        CHECK (place_type IN ('Restaurant', 'FoodStall', 'Area', 'CheckInPoint', 'Other'))
);


-- =========================================================
-- 4. DISH CATEGORIES
-- Danh mục món ăn
-- =========================================================

CREATE TABLE dish_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 5. DISHES
-- Món ăn
-- =========================================================

CREATE TABLE dishes (
    dish_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    dish_name VARCHAR(150) NOT NULL,

    category_id BIGINT NOT NULL,

    description TEXT,
    image_url VARCHAR(500),

    average_price NUMERIC(12, 2),
    is_signature_dish BOOLEAN NOT NULL DEFAULT FALSE,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_dishes_category
        FOREIGN KEY (category_id)
        REFERENCES dish_categories(category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_dishes_average_price
        CHECK (average_price IS NULL OR average_price >= 0)
);


-- =========================================================
-- 6. PLACE DISHES
-- Bảng trung gian: quán nào bán món nào
-- Quan hệ nhiều - nhiều giữa places và dishes
-- =========================================================

CREATE TABLE place_dishes (
    place_dish_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    place_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,

    price NUMERIC(12, 2),
    is_recommended BOOLEAN NOT NULL DEFAULT FALSE,
    note TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_place_dishes_place
        FOREIGN KEY (place_id)
        REFERENCES places(place_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_place_dishes_dish
        FOREIGN KEY (dish_id)
        REFERENCES dishes(dish_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_place_dishes_place_dish
        UNIQUE (place_id, dish_id),

    CONSTRAINT chk_place_dishes_price
        CHECK (price IS NULL OR price >= 0)
);


-- =========================================================
-- 7. NARRATION CONTENTS
-- Nội dung thuyết minh gốc
-- Có thể thuộc Place, Dish hoặc General
-- =========================================================

CREATE TABLE narration_contents (
    narration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(200) NOT NULL,
    original_text TEXT NOT NULL,

    content_type VARCHAR(50) NOT NULL,

    place_id BIGINT,
    dish_id BIGINT,

    created_by BIGINT NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_narration_contents_place
        FOREIGN KEY (place_id)
        REFERENCES places(place_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_narration_contents_dish
        FOREIGN KEY (dish_id)
        REFERENCES dishes(dish_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_narration_contents_created_by
        FOREIGN KEY (created_by)
        REFERENCES admin_users(admin_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_narration_contents_content_type
        CHECK (content_type IN ('Place', 'Dish', 'General')),

    CONSTRAINT chk_narration_contents_target
        CHECK (
            (
                content_type = 'Place'
                AND place_id IS NOT NULL
                AND dish_id IS NULL
            )
            OR
            (
                content_type = 'Dish'
                AND dish_id IS NOT NULL
                AND place_id IS NULL
            )
            OR
            (
                content_type = 'General'
                AND place_id IS NULL
                AND dish_id IS NULL
            )
        )
);


-- =========================================================
-- 8. NARRATION TRANSLATIONS
-- Bản dịch của nội dung thuyết minh theo từng ngôn ngữ
-- =========================================================

CREATE TABLE narration_translations (
    translation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    narration_id BIGINT NOT NULL,
    language_id BIGINT NOT NULL,

    translated_title VARCHAR(200) NOT NULL,
    translated_text TEXT NOT NULL,

    translation_source VARCHAR(50) NOT NULL DEFAULT 'Manual',

    reviewed_by BIGINT,
    is_reviewed BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_narration_translations_narration
        FOREIGN KEY (narration_id)
        REFERENCES narration_contents(narration_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_narration_translations_language
        FOREIGN KEY (language_id)
        REFERENCES languages(language_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_narration_translations_reviewed_by
        FOREIGN KEY (reviewed_by)
        REFERENCES admin_users(admin_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT uq_narration_translations_narration_language
        UNIQUE (narration_id, language_id),

    CONSTRAINT chk_narration_translations_source
        CHECK (translation_source IN ('Manual', 'AI', 'GoogleTranslate'))
);


-- =========================================================
-- 9. AUDIO FILES
-- File âm thanh cho từng bản dịch
-- =========================================================

CREATE TABLE audio_files (
    audio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    translation_id BIGINT NOT NULL,

    audio_url VARCHAR(500) NOT NULL,

    voice_name VARCHAR(100),
    voice_gender VARCHAR(20),

    duration_seconds INTEGER,
    file_format VARCHAR(20) NOT NULL DEFAULT 'mp3',

    generated_by VARCHAR(50) NOT NULL DEFAULT 'TTS',

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audio_files_translation
        FOREIGN KEY (translation_id)
        REFERENCES narration_translations(translation_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_audio_files_voice_gender
        CHECK (
            voice_gender IS NULL
            OR voice_gender IN ('Male', 'Female', 'Neutral')
        ),

    CONSTRAINT chk_audio_files_duration
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0),

    CONSTRAINT chk_audio_files_format
        CHECK (file_format IN ('mp3', 'wav', 'ogg', 'm4a')),

    CONSTRAINT chk_audio_files_generated_by
        CHECK (generated_by IN ('TTS', 'ManualUpload'))
);


-- =========================================================
-- 10. QR CODES
-- QR có thể trỏ đến Place, Dish hoặc Narration
-- Trong 1 dòng chỉ được có 1 target chính
-- =========================================================

CREATE TABLE qr_codes (
    qr_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    qr_code_value VARCHAR(255) NOT NULL UNIQUE,
    qr_code_image_url VARCHAR(500),

    target_type VARCHAR(50) NOT NULL,

    place_id BIGINT,
    dish_id BIGINT,
    narration_id BIGINT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_qr_codes_place
        FOREIGN KEY (place_id)
        REFERENCES places(place_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_qr_codes_dish
        FOREIGN KEY (dish_id)
        REFERENCES dishes(dish_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_qr_codes_narration
        FOREIGN KEY (narration_id)
        REFERENCES narration_contents(narration_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_qr_codes_target_type
        CHECK (target_type IN ('Place', 'Dish', 'Narration')),

    CONSTRAINT chk_qr_codes_target
        CHECK (
            (
                target_type = 'Place'
                AND place_id IS NOT NULL
                AND dish_id IS NULL
                AND narration_id IS NULL
            )
            OR
            (
                target_type = 'Dish'
                AND dish_id IS NOT NULL
                AND place_id IS NULL
                AND narration_id IS NULL
            )
            OR
            (
                target_type = 'Narration'
                AND narration_id IS NOT NULL
                AND place_id IS NULL
                AND dish_id IS NULL
            )
        )
);


-- =========================================================
-- 11. LISTENING HISTORIES
-- Lịch sử nghe của khách anonymous
-- Không có user_id
-- Dùng guest_session_id để phân biệt phiên khách
-- =========================================================

CREATE TABLE listening_histories (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guest_session_id VARCHAR(100),

    narration_id BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    audio_id BIGINT NOT NULL,
    qr_code_id BIGINT,

    listened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    device_info VARCHAR(255),
    ip_address VARCHAR(50),

    listen_duration_seconds INTEGER,

    CONSTRAINT fk_listening_histories_narration
        FOREIGN KEY (narration_id)
        REFERENCES narration_contents(narration_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_listening_histories_language
        FOREIGN KEY (language_id)
        REFERENCES languages(language_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_listening_histories_audio
        FOREIGN KEY (audio_id)
        REFERENCES audio_files(audio_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_listening_histories_qr_code
        FOREIGN KEY (qr_code_id)
        REFERENCES qr_codes(qr_code_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_listening_histories_duration
        CHECK (
            listen_duration_seconds IS NULL
            OR listen_duration_seconds >= 0
        )
);


-- =========================================================
-- 12. FEEDBACKS
-- Phản hồi của khách anonymous
-- Có thể feedback cho Place, Dish hoặc Narration
-- Trong 1 dòng chỉ nên feedback 1 target chính
-- =========================================================

CREATE TABLE feedbacks (
    feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guest_session_id VARCHAR(100),

    place_id BIGINT,
    dish_id BIGINT,
    narration_id BIGINT,

    rating INTEGER NOT NULL,
    comment TEXT,

    is_approved BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_feedbacks_place
        FOREIGN KEY (place_id)
        REFERENCES places(place_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_feedbacks_dish
        FOREIGN KEY (dish_id)
        REFERENCES dishes(dish_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_feedbacks_narration
        FOREIGN KEY (narration_id)
        REFERENCES narration_contents(narration_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_feedbacks_rating
        CHECK (rating BETWEEN 1 AND 5),

    CONSTRAINT chk_feedbacks_target
        CHECK (
            (
                place_id IS NOT NULL
                AND dish_id IS NULL
                AND narration_id IS NULL
            )
            OR
            (
                dish_id IS NOT NULL
                AND place_id IS NULL
                AND narration_id IS NULL
            )
            OR
            (
                narration_id IS NOT NULL
                AND place_id IS NULL
                AND dish_id IS NULL
            )
        )
);


-- =========================================================
-- 13. INDEXES
-- Tạo index cho các khóa ngoại để query nhanh hơn
-- =========================================================

CREATE INDEX idx_dishes_category_id
ON dishes(category_id);

CREATE INDEX idx_place_dishes_place_id
ON place_dishes(place_id);

CREATE INDEX idx_place_dishes_dish_id
ON place_dishes(dish_id);

CREATE INDEX idx_narration_contents_place_id
ON narration_contents(place_id);

CREATE INDEX idx_narration_contents_dish_id
ON narration_contents(dish_id);

CREATE INDEX idx_narration_contents_created_by
ON narration_contents(created_by);

CREATE INDEX idx_narration_translations_narration_id
ON narration_translations(narration_id);

CREATE INDEX idx_narration_translations_language_id
ON narration_translations(language_id);

CREATE INDEX idx_audio_files_translation_id
ON audio_files(translation_id);

CREATE INDEX idx_qr_codes_place_id
ON qr_codes(place_id);

CREATE INDEX idx_qr_codes_dish_id
ON qr_codes(dish_id);

CREATE INDEX idx_qr_codes_narration_id
ON qr_codes(narration_id);

CREATE INDEX idx_listening_histories_guest_session_id
ON listening_histories(guest_session_id);

CREATE INDEX idx_listening_histories_narration_id
ON listening_histories(narration_id);

CREATE INDEX idx_listening_histories_language_id
ON listening_histories(language_id);

CREATE INDEX idx_listening_histories_audio_id
ON listening_histories(audio_id);

CREATE INDEX idx_listening_histories_qr_code_id
ON listening_histories(qr_code_id);

CREATE INDEX idx_feedbacks_guest_session_id
ON feedbacks(guest_session_id);

CREATE INDEX idx_feedbacks_place_id
ON feedbacks(place_id);

CREATE INDEX idx_feedbacks_dish_id
ON feedbacks(dish_id);

CREATE INDEX idx_feedbacks_narration_id
ON feedbacks(narration_id);


-- =========================================================
-- 14. UPDATED_AT TRIGGER
-- Tự động cập nhật updated_at khi update dòng dữ liệu
-- =========================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trg_admin_users_updated_at
BEFORE UPDATE ON admin_users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_languages_updated_at
BEFORE UPDATE ON languages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_places_updated_at
BEFORE UPDATE ON places
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_dish_categories_updated_at
BEFORE UPDATE ON dish_categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_dishes_updated_at
BEFORE UPDATE ON dishes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_place_dishes_updated_at
BEFORE UPDATE ON place_dishes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_narration_contents_updated_at
BEFORE UPDATE ON narration_contents
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_narration_translations_updated_at
BEFORE UPDATE ON narration_translations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_audio_files_updated_at
BEFORE UPDATE ON audio_files
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_qr_codes_updated_at
BEFORE UPDATE ON qr_codes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_feedbacks_updated_at
BEFORE UPDATE ON feedbacks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
-- =========================================================
-- ADD GEOFENCE FIELDS TO PLACES
-- Chạy sau khi đã tạo toàn bộ bảng ban đầu
-- =========================================================

ALTER TABLE places
ADD COLUMN is_poi BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN is_geofence_enabled BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN trigger_radius_meters INTEGER NOT NULL DEFAULT 50,
ADD COLUMN priority INTEGER NOT NULL DEFAULT 1,
ADD COLUMN trigger_mode VARCHAR(20) NOT NULL DEFAULT 'Enter',
ADD COLUMN debounce_seconds INTEGER NOT NULL DEFAULT 10,
ADD COLUMN cooldown_seconds INTEGER NOT NULL DEFAULT 300;

ALTER TABLE places
ADD CONSTRAINT chk_places_trigger_mode
CHECK (trigger_mode IN ('Enter', 'Near', 'Both'));

ALTER TABLE places
ADD CONSTRAINT chk_places_trigger_radius
CHECK (trigger_radius_meters > 0);

ALTER TABLE places
ADD CONSTRAINT chk_places_priority
CHECK (priority >= 0);

ALTER TABLE places
ADD CONSTRAINT chk_places_debounce
CHECK (debounce_seconds >= 0);

ALTER TABLE places
ADD CONSTRAINT chk_places_cooldown
CHECK (cooldown_seconds >= 0);


-- =========================================================
-- GUEST SESSIONS
-- Lưu phiên khách anonymous
-- =========================================================

CREATE TABLE guest_sessions (
    guest_session_id VARCHAR(100) PRIMARY KEY,

    preferred_language_id BIGINT,

    device_info VARCHAR(255),
    ip_address VARCHAR(50),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_guest_sessions_language
        FOREIGN KEY (preferred_language_id)
        REFERENCES languages(language_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


-- =========================================================
-- GUEST POI STATES
-- Lưu trạng thái khách đang ở trong / ngoài vùng POI
-- =========================================================

CREATE TABLE guest_poi_states (
    guest_session_id VARCHAR(100) NOT NULL,
    place_id BIGINT NOT NULL,

    is_inside BOOLEAN NOT NULL DEFAULT FALSE,

    last_entered_at TIMESTAMP,
    last_exited_at TIMESTAMP,
    last_triggered_at TIMESTAMP,
    cooldown_until TIMESTAMP,

    last_distance_meters NUMERIC(10, 2),

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (guest_session_id, place_id),

    CONSTRAINT fk_guest_poi_states_session
        FOREIGN KEY (guest_session_id)
        REFERENCES guest_sessions(guest_session_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_guest_poi_states_place
        FOREIGN KEY (place_id)
        REFERENCES places(place_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- =========================================================
-- GEOFENCE EVENTS
-- Log sự kiện geofence: Enter / Near / Exit
-- =========================================================

CREATE TABLE geofence_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guest_session_id VARCHAR(100) NOT NULL,

    place_id BIGINT NOT NULL,
    narration_id BIGINT,

    event_type VARCHAR(20) NOT NULL,
    event_status VARCHAR(30) NOT NULL DEFAULT 'Detected',

    user_latitude NUMERIC(10, 7),
    user_longitude NUMERIC(10, 7),

    distance_meters NUMERIC(10, 2),

    detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,

    note TEXT,

    CONSTRAINT fk_geofence_events_session
        FOREIGN KEY (guest_session_id)
        REFERENCES guest_sessions(guest_session_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_geofence_events_place
        FOREIGN KEY (place_id)
        REFERENCES places(place_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_geofence_events_narration
        FOREIGN KEY (narration_id)
        REFERENCES narration_contents(narration_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_geofence_events_event_type
        CHECK (event_type IN ('Enter', 'Near', 'Exit')),

    CONSTRAINT chk_geofence_events_status
        CHECK (event_status IN ('Detected', 'IgnoredDebounce', 'IgnoredCooldown', 'Queued', 'Played'))
);


-- =========================================================
-- UPDATE LISTENING HISTORIES
-- Thêm nguồn kích hoạt: QR / Geofence / Manual
-- =========================================================

ALTER TABLE listening_histories
ADD COLUMN geofence_event_id BIGINT,
ADD COLUMN trigger_source VARCHAR(30) NOT NULL DEFAULT 'QR',
ADD COLUMN playback_status VARCHAR(30) NOT NULL DEFAULT 'Played';

ALTER TABLE listening_histories
ADD CONSTRAINT fk_listening_histories_session
FOREIGN KEY (guest_session_id)
REFERENCES guest_sessions(guest_session_id)
ON UPDATE CASCADE
ON DELETE SET NULL;

ALTER TABLE listening_histories
ADD CONSTRAINT fk_listening_histories_geofence_event
FOREIGN KEY (geofence_event_id)
REFERENCES geofence_events(event_id)
ON UPDATE CASCADE
ON DELETE SET NULL;

ALTER TABLE listening_histories
ADD CONSTRAINT chk_listening_histories_trigger_source
CHECK (trigger_source IN ('QR', 'Geofence', 'Manual'));

ALTER TABLE listening_histories
ADD CONSTRAINT chk_listening_histories_playback_status
CHECK (playback_status IN ('Played', 'Skipped', 'Stopped', 'Completed'));


-- =========================================================
-- INDEXES FOR GEOFENCE
-- =========================================================

CREATE INDEX idx_guest_sessions_language_id
ON guest_sessions(preferred_language_id);

CREATE INDEX idx_guest_poi_states_place_id
ON guest_poi_states(place_id);

CREATE INDEX idx_geofence_events_guest_session_id
ON geofence_events(guest_session_id);

CREATE INDEX idx_geofence_events_place_id
ON geofence_events(place_id);

CREATE INDEX idx_geofence_events_narration_id
ON geofence_events(narration_id);

CREATE INDEX idx_listening_histories_geofence_event_id
ON listening_histories(geofence_event_id);


-- =========================================================
-- UPDATED_AT TRIGGER FOR GUEST_POI_STATES
-- Yêu cầu function set_updated_at() đã có từ script trước
-- =========================================================

CREATE TRIGGER trg_guest_poi_states_updated_at
BEFORE UPDATE ON guest_poi_states
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
-- =========================================================
-- 1. LOOKUP TABLES
-- Bỏ hard-code constant, chuyển sang bảng danh mục CRUD
-- =========================================================

CREATE TABLE place_types (
    place_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE content_types (
    content_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE target_types (
    target_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE translation_sources (
    translation_source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trigger_modes (
    trigger_mode_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE geofence_event_types (
    event_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE geofence_event_statuses (
    event_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. SEED DEFAULT LOOKUP DATA
-- Sau này BE có thể CRUD thêm/sửa/xóa mềm bằng is_active
-- =========================================================

INSERT INTO place_types (code, name, description)
VALUES
('Restaurant', 'Restaurant', 'Nhà hàng / quán ăn'),
('FoodStall', 'Food Stall', 'Gian hàng / quầy bán đồ ăn'),
('Area', 'Area', 'Khu vực trong phố ẩm thực'),
('CheckInPoint', 'Check-in Point', 'Điểm check-in'),
('Other', 'Other', 'Loại địa điểm khác')
ON CONFLICT (code) DO NOTHING;

INSERT INTO content_types (code, name, description)
VALUES
('Place', 'Place Narration', 'Thuyết minh cho địa điểm'),
('Dish', 'Dish Narration', 'Thuyết minh cho món ăn'),
('General', 'General Narration', 'Thuyết minh chung')
ON CONFLICT (code) DO NOTHING;

INSERT INTO target_types (code, name, description)
VALUES
('Place', 'Place Target', 'QR / feedback / nội dung trỏ tới địa điểm'),
('Dish', 'Dish Target', 'QR / feedback / nội dung trỏ tới món ăn'),
('Narration', 'Narration Target', 'QR / feedback trỏ trực tiếp tới bài thuyết minh')
ON CONFLICT (code) DO NOTHING;

INSERT INTO translation_sources (code, name, description)
VALUES
('Manual', 'Manual', 'Dịch thủ công'),
('AI', 'AI', 'Dịch bằng AI'),
('GoogleTranslate', 'Google Translate', 'Dịch bằng Google Translate')
ON CONFLICT (code) DO NOTHING;

INSERT INTO trigger_modes (code, name, description)
VALUES
('Enter', 'Enter', 'Kích hoạt khi người dùng đi vào vùng POI'),
('Near', 'Near', 'Kích hoạt khi người dùng đến gần POI'),
('Both', 'Both', 'Kích hoạt cả khi vào vùng và khi đến gần')
ON CONFLICT (code) DO NOTHING;

INSERT INTO geofence_event_types (code, name, description)
VALUES
('Enter', 'Enter', 'Người dùng đi vào vùng POI'),
('Near', 'Near', 'Người dùng đến gần POI'),
('Exit', 'Exit', 'Người dùng rời khỏi vùng POI')
ON CONFLICT (code) DO NOTHING;

INSERT INTO geofence_event_statuses (code, name, description)
VALUES
('Detected', 'Detected', 'Đã phát hiện sự kiện'),
('IgnoredDebounce', 'Ignored Debounce', 'Bỏ qua do debounce'),
('IgnoredCooldown', 'Ignored Cooldown', 'Bỏ qua do cooldown'),
('Queued', 'Queued', 'Đã đưa vào hàng chờ phát'),
('Played', 'Played', 'Đã phát thuyết minh')
ON CONFLICT (code) DO NOTHING;


-- =========================================================
-- 3. DROP OLD CHECK CONSTRAINTS
-- Giữ lại admin_users.role, bỏ các CHECK constant còn lại
-- =========================================================

ALTER TABLE places
DROP CONSTRAINT IF EXISTS chk_places_place_type;

ALTER TABLE places
DROP CONSTRAINT IF EXISTS chk_places_trigger_mode;

ALTER TABLE narration_contents
DROP CONSTRAINT IF EXISTS chk_narration_contents_content_type;

ALTER TABLE narration_contents
DROP CONSTRAINT IF EXISTS chk_narration_contents_target;

ALTER TABLE qr_codes
DROP CONSTRAINT IF EXISTS chk_qr_codes_target_type;

ALTER TABLE qr_codes
DROP CONSTRAINT IF EXISTS chk_qr_codes_target;

ALTER TABLE narration_translations
DROP CONSTRAINT IF EXISTS chk_narration_translations_source;

ALTER TABLE geofence_events
DROP CONSTRAINT IF EXISTS chk_geofence_events_event_type;

ALTER TABLE geofence_events
DROP CONSTRAINT IF EXISTS chk_geofence_events_status;


-- =========================================================
-- 4. MIGRATE places.place_type + places.trigger_mode
-- =========================================================

ALTER TABLE places
ADD COLUMN place_type_id BIGINT,
ADD COLUMN trigger_mode_id BIGINT;

UPDATE places p
SET place_type_id = pt.place_type_id
FROM place_types pt
WHERE p.place_type = pt.code;

UPDATE places p
SET trigger_mode_id = tm.trigger_mode_id
FROM trigger_modes tm
WHERE p.trigger_mode = tm.code;

UPDATE places
SET place_type_id = (
    SELECT place_type_id FROM place_types WHERE code = 'Other'
)
WHERE place_type_id IS NULL;

UPDATE places
SET trigger_mode_id = (
    SELECT trigger_mode_id FROM trigger_modes WHERE code = 'Enter'
)
WHERE trigger_mode_id IS NULL;

ALTER TABLE places
ALTER COLUMN place_type_id SET NOT NULL,
ALTER COLUMN trigger_mode_id SET NOT NULL;

ALTER TABLE places
ADD CONSTRAINT fk_places_place_type
FOREIGN KEY (place_type_id)
REFERENCES place_types(place_type_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE places
ADD CONSTRAINT fk_places_trigger_mode
FOREIGN KEY (trigger_mode_id)
REFERENCES trigger_modes(trigger_mode_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE places
DROP COLUMN place_type,
DROP COLUMN trigger_mode;


-- =========================================================
-- 5. MIGRATE narration_contents.content_type
-- =========================================================

ALTER TABLE narration_contents
ADD COLUMN content_type_id BIGINT;

UPDATE narration_contents nc
SET content_type_id = ct.content_type_id
FROM content_types ct
WHERE nc.content_type = ct.code;

UPDATE narration_contents
SET content_type_id = (
    SELECT content_type_id FROM content_types WHERE code = 'General'
)
WHERE content_type_id IS NULL;

ALTER TABLE narration_contents
ALTER COLUMN content_type_id SET NOT NULL;

ALTER TABLE narration_contents
ADD CONSTRAINT fk_narration_contents_content_type
FOREIGN KEY (content_type_id)
REFERENCES content_types(content_type_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE narration_contents
DROP COLUMN content_type;


-- =========================================================
-- 6. MIGRATE qr_codes.target_type
-- =========================================================

ALTER TABLE qr_codes
ADD COLUMN target_type_id BIGINT;

UPDATE qr_codes q
SET target_type_id = tt.target_type_id
FROM target_types tt
WHERE q.target_type = tt.code;

UPDATE qr_codes
SET target_type_id = (
    SELECT target_type_id FROM target_types WHERE code = 'Narration'
)
WHERE target_type_id IS NULL;

ALTER TABLE qr_codes
ALTER COLUMN target_type_id SET NOT NULL;

ALTER TABLE qr_codes
ADD CONSTRAINT fk_qr_codes_target_type
FOREIGN KEY (target_type_id)
REFERENCES target_types(target_type_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE qr_codes
DROP COLUMN target_type;


-- =========================================================
-- 7. MIGRATE narration_translations.translation_source
-- =========================================================

ALTER TABLE narration_translations
ADD COLUMN translation_source_id BIGINT;

UPDATE narration_translations nt
SET translation_source_id = ts.translation_source_id
FROM translation_sources ts
WHERE nt.translation_source = ts.code;

UPDATE narration_translations
SET translation_source_id = (
    SELECT translation_source_id FROM translation_sources WHERE code = 'Manual'
)
WHERE translation_source_id IS NULL;

ALTER TABLE narration_translations
ALTER COLUMN translation_source_id SET NOT NULL;

ALTER TABLE narration_translations
ADD CONSTRAINT fk_narration_translations_source
FOREIGN KEY (translation_source_id)
REFERENCES translation_sources(translation_source_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE narration_translations
DROP COLUMN translation_source;


-- =========================================================
-- 8. MIGRATE geofence_events.event_type + event_status
-- Chỉ chạy được nếu bạn đã tạo bảng geofence_events trước đó
-- =========================================================

ALTER TABLE geofence_events
ADD COLUMN event_type_id BIGINT,
ADD COLUMN event_status_id BIGINT;

UPDATE geofence_events ge
SET event_type_id = getype.event_type_id
FROM geofence_event_types getype
WHERE ge.event_type = getype.code;

UPDATE geofence_events ge
SET event_status_id = ges.event_status_id
FROM geofence_event_statuses ges
WHERE ge.event_status = ges.code;

UPDATE geofence_events
SET event_type_id = (
    SELECT event_type_id FROM geofence_event_types WHERE code = 'Enter'
)
WHERE event_type_id IS NULL;

UPDATE geofence_events
SET event_status_id = (
    SELECT event_status_id FROM geofence_event_statuses WHERE code = 'Detected'
)
WHERE event_status_id IS NULL;

ALTER TABLE geofence_events
ALTER COLUMN event_type_id SET NOT NULL,
ALTER COLUMN event_status_id SET NOT NULL;

ALTER TABLE geofence_events
ADD CONSTRAINT fk_geofence_events_event_type
FOREIGN KEY (event_type_id)
REFERENCES geofence_event_types(event_type_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE geofence_events
ADD CONSTRAINT fk_geofence_events_event_status
FOREIGN KEY (event_status_id)
REFERENCES geofence_event_statuses(event_status_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE geofence_events
DROP COLUMN event_type,
DROP COLUMN event_status;


-- =========================================================
-- 9. INDEXES FOR LOOKUP FKs
-- =========================================================

CREATE INDEX idx_places_place_type_id
ON places(place_type_id);

CREATE INDEX idx_places_trigger_mode_id
ON places(trigger_mode_id);

CREATE INDEX idx_narration_contents_content_type_id
ON narration_contents(content_type_id);

CREATE INDEX idx_qr_codes_target_type_id
ON qr_codes(target_type_id);

CREATE INDEX idx_narration_translations_source_id
ON narration_translations(translation_source_id);

CREATE INDEX idx_geofence_events_event_type_id
ON geofence_events(event_type_id);

CREATE INDEX idx_geofence_events_event_status_id
ON geofence_events(event_status_id);


-- =========================================================
-- 10. UPDATED_AT TRIGGERS FOR LOOKUP TABLES
-- Yêu cầu function set_updated_at() đã có từ script trước
-- =========================================================

CREATE TRIGGER trg_place_types_updated_at
BEFORE UPDATE ON place_types
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_content_types_updated_at
BEFORE UPDATE ON content_types
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_target_types_updated_at
BEFORE UPDATE ON target_types
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_translation_sources_updated_at
BEFORE UPDATE ON translation_sources
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_trigger_modes_updated_at
BEFORE UPDATE ON trigger_modes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_geofence_event_types_updated_at
BEFORE UPDATE ON geofence_event_types
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_geofence_event_statuses_updated_at
BEFORE UPDATE ON geofence_event_statuses
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

