BEGIN;

UPDATE public.languages
SET is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE language_code IN ('vi', 'en', 'ja', 'ko', 'zh');

UPDATE public.audio_files
SET is_active = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE audio_url IS NULL OR btrim(audio_url) = '';

INSERT INTO public.translation_sources (code, name, description, is_active)
VALUES ('AI', 'AI', 'Dịch tự động bằng API dịch', TRUE)
ON CONFLICT (code) DO UPDATE
SET is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

COMMIT;

SELECT
    nc.narration_id,
    nc.title,
    string_agg(l.language_code, ', ' ORDER BY l.language_code) AS missing_languages
FROM public.narration_contents nc
CROSS JOIN public.languages l
LEFT JOIN public.narration_translations nt
    ON nt.narration_id = nc.narration_id
   AND nt.language_id = l.language_id
WHERE nc.is_active = TRUE
  AND l.is_active = TRUE
  AND l.language_code IN ('vi', 'en', 'ja', 'ko', 'zh')
  AND nt.translation_id IS NULL
GROUP BY nc.narration_id, nc.title
ORDER BY nc.narration_id;

SELECT
    nc.narration_id,
    nc.title AS original_title,
    l.language_code,
    nt.translated_title,
    nt.translated_text
FROM public.narration_contents nc
JOIN public.narration_translations nt
    ON nt.narration_id = nc.narration_id
JOIN public.languages l
    ON l.language_id = nt.language_id
WHERE nc.is_active = TRUE
ORDER BY nc.narration_id, l.language_code
LIMIT 20;

CREATE TABLE IF NOT EXISTS public.admin_refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_ip VARCHAR(100) NULL,
    revoked_by_ip VARCHAR(100) NULL,
    replaced_by_token_hash VARCHAR(255) NULL,

    CONSTRAINT fk_admin_refresh_tokens_admin
        FOREIGN KEY (admin_id)
        REFERENCES public.admin_users(admin_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admin_refresh_tokens_admin_id
ON public.admin_refresh_tokens(admin_id);

CREATE INDEX IF NOT EXISTS idx_admin_refresh_tokens_token_hash
ON public.admin_refresh_tokens(token_hash);